### PR TITLE
addition of calc_trigger_rates

### PR DESCRIPTION
**Pull request by somusset**
Addition of Athiray's procedure calc_trigger_rates

### CODE REVIEW

**Comment by LinErinG** [comment]
Some light/easy comments:

-- I think the header should include a description of what the return values are from the function (i.e. it is an array of 7 numbers that contain the nonzero event rate for the 7 detectors, and the units are triggers per second).  Although it's easy to figure out, this would improve the documentation.

-- I suggest to replace the keyword LOUD with a complementary keyword QUIET if you want LOUD to be the default.  (It's more intuitive to set /QUIET than it is to set LOUD=0.)

**Comment by somusset** [comment]
I added the description of the output and a quiet keyword.

**Review by pymilo — COMMENTED** [review]
Tested with the command:
rate = calc_trigger_rates('test_data.dat')
inside my local CalSoft using an old formatter file from the calibration with sealed sources on D101. 
After printing each step the function was doing, the final result is: 
rate = 
       1.6024881601333618       2.7366781234741211
       20.575473785400391       221.08407592773438
       13.934335708618164       2.3118507862091064
       21.383632659912109
 - Which is pretty much an standard set of expected values. - 

I agree with Lindsay comments about changing the way the keyword "Loud" and "quiet" are called since I only got this procedure to run in SSW but not in the standard IDL 8.7 I think due to the lack of command DEFAULT.

**Review by pymilo — COMMENTED** [review]
This is not a crucial commend since most people running CalSoft will load SSW, but if possible we should try to keep the same style Lindsay uses for set keywords that avoids the use of the command: "DEFAULT".

**Pull request merged**
